import 'voice_generation_service.dart';

class AliyunVoiceList {
  static final List<AliyunVoiceType> cosyVoiceV1List = [
    AliyunVoiceType(
      '龙小诚',
      'longxiaocheng',
      '语音助手、导航播报、聊天数字人',
      '龙小诚(男声) - 中文普通话+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/xrqksx/%E9%BE%99%E5%B0%8F%E8%AF%9A.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙小白',
      'longxiaobai',
      '聊天数字人、有声书、语音助手',
      '龙小白(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/vusvze/%E9%BE%99%E5%B0%8F%E7%99%BD.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙老铁',
      'longlaotie',
      '新闻播报、有声书、语音助手、直播带货、导航播报',
      '龙老铁(男声) - 中文东北口音',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/pfsfir/%E9%BE%99%E8%80%81%E9%93%81.mp3',
      'network',
    ),

    AliyunVoiceType(
      '龙硕',
      'longshuo',
      '语音助手、导航播报、新闻播报、客服催收',
      '龙硕(男声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/lcykpl/%E9%BE%99%E7%A1%95.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙婧',
      'longjing',
      '语音助手、导航播报、新闻播报、客服催收',
      '龙婧(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/ozkbmb/%E9%BE%99%E5%A9%A7.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙妙',
      'longmiao',
      '客服催收、导航播报、有声书、语音助手',
      '龙妙(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/zjnqis/%E9%BE%99%E5%A6%99.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙悦',
      'longyue',
      '语音助手、诗词朗诵、有声书朗读、导航播报、新闻播报、客服催收',
      '龙悦(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/nrkjqf/%E9%BE%99%E6%82%A6.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙媛',
      'longyuan',
      '有声书、语音助手、聊天数字人',
      '龙媛(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/xuboos/%E9%BE%99%E5%AA%9B.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙飞',
      'longfei',
      '会议播报、新闻播报、有声书',
      '龙飞(男声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/bhkjjx/%E9%BE%99%E9%A3%9E.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙杰力豆',
      'longjielidou',
      '新闻播报、有声书、聊天助手',
      '龙杰力豆(女声) - 中文普通话+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/dctiyg/%E9%BE%99%E6%9D%B0%E5%8A%9B%E8%B1%86.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙彤',
      'longtong',
      '有声书、导航播报、聊天数字人',
      '龙彤(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/qyqmvo/%E9%BE%99%E5%BD%A4.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙祥',
      'longxiang',
      '新闻播报、有声书、导航播报',
      '龙祥(男声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/jybshd/%E9%BE%99%E7%A5%A5.mp3',
      'network',
    ),
    AliyunVoiceType(
      'Stella',
      'loongstella',
      '语音助手、直播带货、导航播报、客服催收、有声书',
      'Stella(女声) - 中文普通话+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/haffms/Stella.mp3',
      'network',
    ),
  ];

  static final List<AliyunVoiceType> cosyVoiceV2List = [
    AliyunVoiceType(
      '龙橙',
      'longcheng',
      '语音助手、导航播报、聊天数字人',
      '龙橙(男声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/ggjwfl/%E9%BE%99%E6%A9%99.wav',
      'network',
    ),
    AliyunVoiceType(
      '龙华',
      'longhua',
      '语音助手、导航播报、聊天数字人',
      '龙华(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/jpjtvy/%E9%BE%99%E5%8D%8E.wav',
      'network',
    ),
    AliyunVoiceType(
      '龙书',
      'longshu',
      '有声书、语音助手、导航播报、新闻播报、智能客服',
      '龙书(男声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/azcerd/%E9%BE%99%E4%B9%A6.mp3',
      'network',
    ),
    AliyunVoiceType(
      'Bella',
      'loongbella',
      '语音助手、客服催收、新闻播报、导航播报',
      'Bella(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/tguine/Bella.mp3',
      'network',
    ),
    AliyunVoiceType(
      "龙婉",
      'longwan',
      '语音助手、导航播报、聊天数字人',
      '龙婉(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240830/dzkngm/%E9%BE%99%E5%A9%89.mp3',
      'network',
    ),
    AliyunVoiceType(
      "龙小淳",
      "longxiaochun",
      '语音助手、导航播报、聊天数字人',
      '龙小淳(女声) - 中文普通话+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/rlfvcd/%E9%BE%99%E5%B0%8F%E6%B7%B3.mp3',
      'network',
    ),
    AliyunVoiceType(
      '龙小夏',
      'longxiaoxia',
      '语音助手、聊天数字人',
      '龙小夏(女声) - 中文普通话',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20240624/wzywtu/%E9%BE%99%E5%B0%8F%E5%A4%8F.mp3',
      'network',
    ),
  ];

  static final List<AliyunVoiceType> sambertList = [
    AliyunVoiceType(
      '知楠',
      'zhinan',
      '通用场景',
      '知楠 - 广告男声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230713/cymq/知楠.wav',
      'network',
    ),
    AliyunVoiceType(
      '知琪',
      'zhiqi',
      '通用场景',
      '知琪 - 温柔女声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230712/wnqs/知琪.wav',
      'network',
    ),
  ];

  static final List<AliyunVoiceType> qwenTTSList = [
    AliyunVoiceType(
      '切瑞',
      'Cherry',
      '通用场景',
      'Cherry - 女声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250211/tixcef/cherry.wav',
      'network',
    ),
    AliyunVoiceType(
      '切尔西',
      'Chelsie',
      '通用场景',
      'Chelsie - 女声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250211/vnpxgw/chelsie.wav',
      'network',
    ),
    AliyunVoiceType(
      '塞雷娜',
      'Serena',
      '通用场景',
      'Serena - 女声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250211/bxokea/serena.wav',
      'network',
    ),
    AliyunVoiceType(
      '伊桑',
      'Ethan',
      '通用场景',
      'Ethan - 男声 - 中文+英文',
      'https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20250211/emaqdp/ethan.wav',
      'network',
    ),
  ];
}
